# Generated by Django 4.0.6 on 2022-07-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_doctoblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoblog',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
