# Generated by Django 4.0.6 on 2022-07-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_doctoblog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoblog',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='doctoblog',
            name='summary',
            field=models.CharField(max_length=100),
        ),
    ]
